### ISSUE TITLE
Credentials cannot be validated with Google API.

### ISSUE THREAD

**Issue by CodeMeZone** [maurocasas/fastindex#1]
Uploaded the credentials.json

**Comment by CodeMeZone** [comment]
Fixed. Logged in and out.

**Comment by maurocasas** [comment]
Hey @CodeMeZone thanks for sharing the insight

Can you share what you did so I can try to recreate here and avoid the in-n-out methodology?

**Comment by bpolaszek** [comment]
Hi, doesn't work for me.
Followed instructions: 
- https://console.cloud.google.com/ -> select a project
- https://console.cloud.google.com/iam-admin/serviceaccounts
- Create service account
- Keys -> Add -> Json -> Download
- FastIndex -> Service Account -> Link service account
<img width="513" alt="Capture d’écran 2024-11-19 à 09 28 00" src="https://github.com/user-attachments/assets/71a50460-2819-4332-96f8-28026daa889c">

Logging in & out didn't help.
By the way, the _Learn how to create a service account_ link is broken, nothing happens when you click on it.

Thanks!
Ben

**UPDATE**: Using the credentials file by myself gave me a more detailed error: 
> Google Search Console API has not been used in project before or it is disabled.

You actually have to explicitely allow Google Search Console API by [clicking here](https://console.developers.google.com/apis/api/searchconsole.googleapis.com/overview).

**UPDATE 2**: @maurocasas  my `credentials.json` file is now accepted by Google, however site list remains empty (even when performing the API lookup by myself). It looks like "service accounts" are purely [not allowed to list websites](https://github.com/googleapis/google-api-php-client/issues/1144#issuecomment-278805422) on search console, only regular oauth2 tokens (which are way more complicated to obtain & renew, esp. when working for somebody else) do. If true, how can your app even work? 🤔

**Comment by maurocasas** [comment]
Hey @bpolaszek 

Project has been deprecated sadly as Google has made the API being used useless for non-live streaming platforms.

I wouldn't recommend using it, as it could end up in your site getting penalized.

**Comment by bpolaszek** [comment]
Too bad :-/ 
Thanks anyway!
